name : main
on :
  push :
    branches:
    - main
jobs:
  build-deploy:
    runs-on : Ubuntu-latest
 
    steps :
    - name : Checkout
      uses : actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name : Copy project file on EC2
      run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 777 ec2_key.pem 
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/GitHub-Action_test/Shopify
          sudo git remote set-url origin https://11kamleshm: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@github.com:11kamleshm/GitHub-Action_test.git
          sudo git pull origin main
          sudo npm install
          sudo npm run build
          sudo pm2 start npm --name Shopify --start
          EOF 
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
