name : main
on :
  push :
    branches:
    - main

jobs:
  build-deploy:
    runs-on : Ubuntu-latest

    steps :
    - name : Checkout
      uses : actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name : Copy project file on EC2
      run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@54.197.16.41 << 'EOF'
          cd ~/my-node-app       # <-- yeh path aapke project ke hisaab se set karein
          git pull origin main
          npm install
          pm2 restart all || pm2 start index.js --name "myapp"
          EOF
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          
